/*

   This code uses GARMIN FIT SDK V21.141.00 (https://developer.garmin.com/downloads/fit/sdk/FitSDKRelease_21.141.00.zip)
   Under the Flexible and Interoperable Data Transfer (FIT) Protocol License:
   (https://www.thisisant.com/developer/ant/licensing/flexible-and-interoperable-data-transfer-fit-protocol-license).

	Convert fit fields definition to string title.
   Copyright (C) <2024>  Yoram Finder

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <fit_example.h>

#define MESG_TITLES 66

static char *unknown = "unknown";

typedef struct {
	FIT_UINT8 f_val;
	char *f_title;
} _field_title;

typedef struct {
	FIT_MESG_NUM g_mesg_num;
	FIT_UINT8 num_of_fields;
	_field_title *fields;
	char *mesg_title;
} _mesg_titles;

static _field_title file_id_mesg[FIT_FILE_ID_MESG_FIELDS] = {
	{FIT_FILE_ID_FIELD_NUM_SERIAL_NUMBER, "SERIAL_NUMBER"},
	{FIT_FILE_ID_FIELD_NUM_TIME_CREATED, "TIME_CREATED"},
	{FIT_FILE_ID_FIELD_NUM_PRODUCT_NAME, "PRODUCT_NAME"},
	{FIT_FILE_ID_FIELD_NUM_MANUFACTURER, "MANUFACTURER"},
	{FIT_FILE_ID_FIELD_NUM_PRODUCT, "PRODUCT"},
	{FIT_FILE_ID_FIELD_NUM_NUMBER, "NUMBER"},
	{FIT_FILE_ID_FIELD_NUM_TYPE, "TYPE"}
};

static _field_title file_creator_mesg[FIT_FILE_CREATOR_MESG_FIELDS] = {
	{FIT_FILE_CREATOR_MESG_SOFTWARE_VERSION, "SOFTWARE_VERSION"},
	{FIT_FILE_CREATOR_MESG_HARDWARE_VERSION, "HARDWARE_VERSION"}
};

static _field_title software_mesg[FIT_SOFTWARE_MESG_FIELDS] = {
	{FIT_SOFTWARE_FIELD_NUM_PART_NUMBER, "PART_NUMBER"},
	{FIT_SOFTWARE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SOFTWARE_FIELD_NUM_VERSION, "VERSION"}
};

static _field_title slave_device_mesg[FIT_SLAVE_DEVICE_MESG_FIELDS] = {
	{FIT_SLAVE_DEVICE_FIELD_NUM_MANUFACTURER, "MANUFACTURER"},
	{FIT_SLAVE_DEVICE_FIELD_NUM_PRODUCT, "PRODUCT"}
};

static _field_title capabilities_mesg[FIT_CAPABILITIES_MESG_FIELDS] = {
	{FIT_CAPABILITIES_FIELD_NUM_LANGUAGES, "LANGUAGES"},
	{FIT_CAPABILITIES_FIELD_NUM_WORKOUTS_SUPPORTED, "WORKOUTS_SUPPORTED"},
	{FIT_CAPABILITIES_FIELD_NUM_CONNECTIVITY_SUPPORTED, "CONNECTIVITY_SUPPORTED"},
	{FIT_CAPABILITIES_FIELD_NUM_SPORTS, "SPORTS"}
};

static _field_title file_capabilities_mesg[FIT_FILE_CAPABILITIES_MESG_FIELDS] = {
	{FIT_FILE_CAPABILITIES_FIELD_NUM_DIRECTORY, "DIRECTORY"},
	{FIT_FILE_CAPABILITIES_FIELD_NUM_MAX_SIZE, "MAX_SIZE"},
	{FIT_FILE_CAPABILITIES_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_FILE_CAPABILITIES_FIELD_NUM_MAX_COUNT, "MAX_COUNT"},
	{FIT_FILE_CAPABILITIES_FIELD_NUM_TYPE, "TYPE"},
	{FIT_FILE_CAPABILITIES_FIELD_NUM_FLAGS, "FLAGS"}
};

static _field_title mesg_capabilities_mesg[FIT_MESG_CAPABILITIES_MESG_FIELDS] = {
	{FIT_MESG_CAPABILITIES_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_MESG_CAPABILITIES_FIELD_NUM_MESG_NUM, "MESG_NUM"},
	{FIT_MESG_CAPABILITIES_FIELD_NUM_COUNT, "COUNT"},
	{FIT_MESG_CAPABILITIES_FIELD_NUM_FILE, "FILE"},
	{FIT_MESG_CAPABILITIES_FIELD_NUM_COUNT_TYPE, "COUNT_TYPE"}
};

static _field_title field_capabilities_mesg[FIT_FIELD_CAPABILITIES_MESG_FIELDS] = {
	{FIT_FIELD_CAPABILITIES_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_FIELD_CAPABILITIES_FIELD_NUM_MESG_NUM, "MESG_NUM"},
	{FIT_FIELD_CAPABILITIES_FIELD_NUM_COUNT, "COUNT"},
	{FIT_FIELD_CAPABILITIES_FIELD_NUM_FILE, "FILE"},
	{FIT_FIELD_CAPABILITIES_FIELD_NUM_FIELD_NUM, "FIELD_NUM"}
};

static _field_title device_settings_mesg[FIT_DEVICE_SETTINGS_MESG_FIELDS] = {
	{FIT_DEVICE_SETTINGS_FIELD_NUM_UTC_OFFSET, "UTC_OFFSET"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_UTC_OFFSET, "TIME_OFFSET"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_CLOCK_TIME, "CLOCK_TIME"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_PAGES_ENABLED, "PAGES_ENABLED"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_DEFAULT_PAGE, "DEFAULT_PAGE"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_AUTOSYNC_MIN_STEPS, "AUTOSYNC_MIN_STEPS"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_AUTOSYNC_MIN_TIME, "AUTOSYNC_MIN_TIME"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_ACTIVE_TIME_ZONE, "ACTIVE_TIME_ZONE"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_TIME_MODE, "TIME_MODE"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_TIME_ZONE_OFFSET, "TIME_ZONE_OFFSET"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_BACKLIGHT_MODE, "BACKLIGHT_MODE"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_ACTIVITY_TRACKER_ENABLED,"ACTIVITY_TRACKER_ENABLED"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_MOVE_ALERT_ENABLED,"MOVE_ALERT_ENABLED"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_DATE_MODE, "DATE_MODE"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_DISPLAY_ORIENTATION, "DISPLAY_ORIENTATION"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_MOUNTING_SIDE, "MOUNTING_SIDE"},
	{FIT_DEVICE_SETTINGS_FIELD_NUM_TAP_SENSITIVITY, "TAP_SENSITIVITY"}
};

static _field_title user_profile_mesg[FIT_USER_PROFILE_MESG_FIELDS] = {
	{FIT_USER_PROFILE_FIELD_NUM_FRIENDLY_NAME, "FRIENDLY_NAME"},
	{FIT_USER_PROFILE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_USER_PROFILE_FIELD_NUM_WEIGHT, "WEIGHT"},
	{FIT_USER_PROFILE_FIELD_NUM_LOCAL_ID, "LOCAL_ID"},
	{FIT_USER_PROFILE_FIELD_NUM_USER_RUNNING_STEP_LENGTH, "USER_RUNNING_STEP_LENGTH"},
	{FIT_USER_PROFILE_FIELD_NUM_USER_WALKING_STEP_LENGTH, "USER_WALKING_STEP_LENGTH"},
	{FIT_USER_PROFILE_FIELD_NUM_GENDER, "GENDER"},
	{FIT_USER_PROFILE_FIELD_NUM_AGE, "AGE"},
	{FIT_USER_PROFILE_FIELD_NUM_HEIGHT, "HEIGHT"},
	{FIT_USER_PROFILE_FIELD_NUM_LANGUAGE, "LANGUAGE"},
	{FIT_USER_PROFILE_FIELD_NUM_ELEV_SETTING, "ELEV_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_WEIGHT_SETTING, "WEIGHT_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_RESTING_HEART_RATE, "RESTING_HEART_RATE"},
	{FIT_USER_PROFILE_FIELD_NUM_DEFAULT_MAX_RUNNING_HEART_RATE, "DEFAULT_MAX_RUNNING_HEART_RATE"},
	{FIT_USER_PROFILE_FIELD_NUM_DEFAULT_MAX_BIKING_HEART_RATE, "DEFAULT_MAX_BIKING_HEART_RATE"},
	{FIT_USER_PROFILE_FIELD_NUM_DEFAULT_MAX_HEART_RATE, "DEFAULT_MAX_HEART_RATE"},
	{FIT_USER_PROFILE_FIELD_NUM_HR_SETTING, "HR_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_SPEED_SETTING, "SPEED_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_DIST_SETTING, "DIST_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_POWER_SETTING, "POWER_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_ACTIVITY_CLASS, "ACTIVITY_CLASS"},
	{FIT_USER_PROFILE_FIELD_NUM_POSITION_SETTING, "POSITION_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_TEMPERATURE_SETTING, "TEMPERATURE_SETTING"},
	{FIT_USER_PROFILE_FIELD_NUM_GLOBAL_ID, "GLOBAL_ID"},
	{FIT_USER_PROFILE_FIELD_NUM_HEIGHT_SETTING, "HEIGHT_SETTING"}
};

static _field_title hrm_profile_mesg[FIT_HRM_PROFILE_MESG_FIELDS] = {
	{FIT_HRM_PROFILE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_HRM_PROFILE_FIELD_NUM_HRM_ANT_ID, "HRM_ANT_ID"},
	{FIT_HRM_PROFILE_FIELD_NUM_ENABLED, "ENABLED"},
	{FIT_HRM_PROFILE_FIELD_NUM_LOG_HRV, "LOG_HRV"},
	{FIT_HRM_PROFILE_FIELD_NUM_HRM_ANT_ID_TRANS_TYPE, "HRM_ANT_ID_TRANS_TYPE"}
};

static _field_title sdm_profile_mesg[FIT_SDM_PROFILE_MESG_FIELDS] = {
	{FIT_SDM_PROFILE_FIELD_NUM_ODOMETER, "ODOMETER"},
	{FIT_SDM_PROFILE_FIELD_NUM_MESSAGE_INDEX, "INDEX"},
	{FIT_SDM_PROFILE_FIELD_NUM_SDM_ANT_ID, "SDM_ANT_ID"},
	{FIT_SDM_PROFILE_FIELD_NUM_SDM_CAL_FACTOR, "SDM_CAL_FACTOR"},
	{FIT_SDM_PROFILE_FIELD_NUM_ENABLED, "ENABLED"},
	{FIT_SDM_PROFILE_FIELD_NUM_SPEED_SOURCE, "SPEED_SOURCE"},
	{FIT_SDM_PROFILE_FIELD_NUM_SDM_ANT_ID_TRANS_TYPE, "SDM_ANT_ID_TRANS_TYPE"},
	{FIT_SDM_PROFILE_FIELD_NUM_ODOMETER_ROLLOVER, "ODOMETER_ROLLOVER"}
};

static _field_title bike_profile_mesg[FIT_BIKE_PROFILE_MESG_FIELDS] = {
	{FIT_BIKE_PROFILE_FIELD_NUM_NAME, "NAME"},
	{FIT_BIKE_PROFILE_FIELD_NUM_ODOMETER, "ODOMETER"},
	{FIT_BIKE_PROFILE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_SPD_ANT_ID, "BIKE_SPD_ANT_ID"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_CAD_ANT_ID, "BIKE_CAD_ANT_ID"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_SPDCAD_ANT_ID, "BIKE_SPDCAD_ANT_ID"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_POWER_ANT_ID, "BIKE_POWER_ANT_ID"},
	{FIT_BIKE_PROFILE_FIELD_NUM_CUSTOM_WHEELSIZE, "CUSTOM_WHEELSIZE"},
	{FIT_BIKE_PROFILE_FIELD_NUM_AUTO_WHEELSIZE, "AUTO_WHEELSIZE"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_WEIGHT, "BIKE_WEIGHT"},
	{FIT_BIKE_PROFILE_FIELD_NUM_POWER_CAL_FACTOR, "POWER_CAL_FACTOR"},
	{FIT_BIKE_PROFILE_FIELD_NUM_SPORT, "SPORT"},
	{FIT_BIKE_PROFILE_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_BIKE_PROFILE_FIELD_NUM_AUTO_WHEEL_CAL, "AUTO_WHEEL_CAL"},
	{FIT_BIKE_PROFILE_FIELD_NUM_AUTO_POWER_ZERO, "AUTO_POWER_ZERO"},
	{FIT_BIKE_PROFILE_FIELD_NUM_ID, "ID"},
	{FIT_BIKE_PROFILE_FIELD_NUM_SPD_ENABLED, "SPD_ENABLED"},
	{FIT_BIKE_PROFILE_FIELD_NUM_CAD_ENABLED, "CAD_ENABLED"},
	{FIT_BIKE_PROFILE_FIELD_NUM_SPDCAD_ENABLED, "SPDCAD_ENABLED"},
	{FIT_BIKE_PROFILE_FIELD_NUM_POWER_ENABLED, "POWER_ENABLED"},
	{FIT_BIKE_PROFILE_FIELD_NUM_CRANK_LENGTH, "CRANK_LENGTH"},
	{FIT_BIKE_PROFILE_FIELD_NUM_ENABLED, "ENABLED"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_SPD_ANT_ID_TRANS_TYPE, "BIKE_SPD_ANT_ID_TRANS_TYPE"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_CAD_ANT_ID_TRANS_TYPE, "BIKE_CAD_ANT_ID_TRANS_TYPE"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_SPDCAD_ANT_ID_TRANS_TYPE, "BIKE_SPDCAD_ANT_ID_TRANS_TYPE"},
	{FIT_BIKE_PROFILE_FIELD_NUM_BIKE_POWER_ANT_ID_TRANS_TYPE, "BIKE_POWER_ANT_ID_TRANS_TYPE"},
	{FIT_BIKE_PROFILE_FIELD_NUM_ODOMETER_ROLLOVER, "ODOMETER_ROLLOVER"},
	{FIT_BIKE_PROFILE_FIELD_NUM_FRONT_GEAR_NUM, "FRONT_GEAR_NUM"},
	{FIT_BIKE_PROFILE_FIELD_NUM_FRONT_GEAR, "FRONT_GEAR"},
	{FIT_BIKE_PROFILE_FIELD_NUM_REAR_GEAR_NUM, "REAR_GEAR_NUM"},
	{FIT_BIKE_PROFILE_FIELD_NUM_REAR_GEAR, "REAR_GEAR"},
	{FIT_BIKE_PROFILE_FIELD_NUM_SHIMANO_DI2_ENABLED, "SHIMANO_DI2_ENABLED"}
};

static _field_title connectivity_mesg[FIT_CONNECTIVITY_MESG_FIELDS] = {
	{FIT_CONNECTIVITY_FIELD_NUM_NAME, "NAME"},
	{FIT_CONNECTIVITY_FIELD_NUM_BLUETOOTH_ENABLED, "BLUETOOTH_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_BLUETOOTH_LE_ENABLED, "BLUETOOTH_LE_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_ANT_ENABLED, "ANT_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_LIVE_TRACKING_ENABLED, "LIVE_TRACKING_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_WEATHER_CONDITIONS_ENABLED, "WEATHER_CONDITIONS_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_WEATHER_ALERTS_ENABLED, "WEATHER_ALERTS_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_AUTO_ACTIVITY_UPLOAD_ENABLED, "AUTO_ACTIVITY_UPLOAD_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_COURSE_DOWNLOAD_ENABLED, "COURSE_DOWNLOAD_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_WORKOUT_DOWNLOAD_ENABLED, "WORKOUT_DOWNLOAD_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_GPS_EPHEMERIS_DOWNLOAD_ENABLED, "GPS_EPHEMERIS_DOWNLOAD_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_INCIDENT_DETECTION_ENABLED, "INCIDENT_DETECTION_ENABLED"},
	{FIT_CONNECTIVITY_FIELD_NUM_GROUPTRACK_ENABLED, "GROUPTRACK_ENABLED"}
};

static _field_title zones_target_mesg[FIT_ZONES_TARGET_MESG_FIELDS] = {
	{FIT_ZONES_TARGET_FIELD_NUM_FUNCTIONAL_THRESHOLD_POWER, "FUNCTIONAL_THRESHOLD_POWER"},
	{FIT_ZONES_TARGET_FIELD_NUM_MAX_HEART_RATE, "MAX_HEART_RATE"},
	{FIT_ZONES_TARGET_FIELD_NUM_THRESHOLD_HEART_RATE, "THRESHOLD_HEART_RATE"},
	{FIT_ZONES_TARGET_FIELD_NUM_HR_CALC_TYPE, "HR_CALC_TYPE"},
	{FIT_ZONES_TARGET_FIELD_NUM_PWR_CALC_TYPE, "PWR_CALC_TYPE"}
};

static _field_title sport_mesg[FIT_SPORT_MESG_FIELDS] = {
	{FIT_SPORT_FIELD_NUM_NAME, "NAME"},
	{FIT_SPORT_FIELD_NUM_SPORT, "SPORT"},
	{FIT_SPORT_FIELD_NUM_SUB_SPORT, "SU_SPORT"}
};

static _field_title hr_zone_mesg[FIT_HR_ZONE_MESG_FIELDS] = {
	{FIT_HR_ZONE_FIELD_NUM_NAME, "NAME"},
	{FIT_HR_ZONE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_HR_ZONE_FIELD_NUM_HIGH_BPM, "HIGH_BPM"}
};

static _field_title speed_zone_mesg[FIT_SPEED_ZONE_MESG_FIELDS] = {
	{FIT_SPEED_ZONE_FIELD_NUM_NAME, "NAME"},
	{FIT_SPEED_ZONE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SPEED_ZONE_FIELD_NUM_HIGH_VALUE, "HIGH_VALUE"}
};

static _field_title cadence_zone_mesg[FIT_CADENCE_ZONE_MESG_FIELDS] = {
	{FIT_CADENCE_ZONE_FIELD_NUM_NAME, "NAME"},
	{FIT_CADENCE_ZONE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_CADENCE_ZONE_FIELD_NUM_HIGH_VALUE, "HIGH_VALUE"}
};

static _field_title power_zone_mesg[FIT_POWER_ZONE_MESG_FIELDS] = {
	{FIT_POWER_ZONE_FIELD_NUM_NAME, "NAME"},
	{FIT_POWER_ZONE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_POWER_ZONE_FIELD_NUM_HIGH_VALUE, "HIGH_VALUE"}
};

static _field_title met_zone_mesg[FIT_MET_ZONE_MESG_FIELDS] = {
	{FIT_MET_ZONE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_MET_ZONE_FIELD_NUM_CALORIES, "CALORIES"},
	{FIT_MET_ZONE_FIELD_NUM_HIGH_BPM, "HIGH_BPM"},
	{FIT_MET_ZONE_FIELD_NUM_FAT_CALORIES, "FAT_CALORIES"}
};

static _field_title dive_settings_mesg[FIT_DIVE_SETTINGS_MESG_FIELDS] ={
	{FIT_DIVE_SETTINGS_FIELD_NUM_NAME, "NAME"},
	{FIT_DIVE_SETTINGS_FIELD_NUM_HEART_RATE_SOURCE, "HEART_RATE_SOURCE"}
};

static _field_title goal_mesg[FIT_GOAL_MESG_FIELDS] ={
	{FIT_GOAL_FIELD_NUM_START_DATE, "START_DATE"},
	{FIT_GOAL_FIELD_NUM_END_DATE, "END_DATE"},
	{FIT_GOAL_FIELD_NUM_VALUE, "VALUE"},
	{FIT_GOAL_FIELD_NUM_TARGET_VALUE, "TARGET_VALUE"},
	{FIT_GOAL_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_GOAL_FIELD_NUM_RECURRENCE_VALUE, "RECURRENCE_VALUE"},
	{FIT_GOAL_FIELD_NUM_SPORT, "SPORT"},
	{FIT_GOAL_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_GOAL_FIELD_NUM_TYPE, "TYPE"},
	{FIT_GOAL_FIELD_NUM_REPEAT, "REPEAT"},
	{FIT_GOAL_FIELD_NUM_RECURRENCE, "RECURRENCE"},
	{FIT_GOAL_FIELD_NUM_ENABLED, "ENABLED"},
	{FIT_GOAL_FIELD_NUM_SOURCE, "SOURCE"}
};

static _field_title activity_mesg[FIT_ACTIVITY_MESG_FIELDS] = {
	{FIT_ACTIVITY_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_ACTIVITY_FIELD_NUM_TOTAL_TIMER_TIME, "TOTAL_TIMER_TIME"},
	{FIT_ACTIVITY_FIELD_NUM_LOCAL_TIMESTAMP, "LOCAL_TIMESTAMP"},
	{FIT_ACTIVITY_FIELD_NUM_NUM_SESSIONS, "NUM_SESSIONS"},
	{FIT_ACTIVITY_FIELD_NUM_TYPE, "TYPE"},
	{FIT_ACTIVITY_FIELD_NUM_EVENT, "EVENT"},
	{FIT_ACTIVITY_FIELD_NUM_EVENT_TYPE, "EVENT_TYPE"},
	{FIT_ACTIVITY_FIELD_NUM_EVENT_GROUP, "EVENT_GROUP"}
};

static _field_title session_mesg[FIT_SESSION_MESG_FIELDS] ={
	{FIT_SESSION_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_SESSION_FIELD_NUM_START_TIME, "START_TIME"},
	{FIT_SESSION_FIELD_NUM_START_POSITION_LAT, "START_POSITION_LAT"},
	{FIT_SESSION_FIELD_NUM_START_POSITION_LONG, "START_POSITION_LONG"},
	{FIT_SESSION_FIELD_NUM_TOTAL_ELAPSED_TIME, "TOTAL_ELAPSED_TIME"},
	{FIT_SESSION_FIELD_NUM_TOTAL_TIMER_TIME, "TOTAL_TIMER_TIME"},
	{FIT_SESSION_FIELD_NUM_TOTAL_DISTANCE, "TOTAL_DISTANCE"},
	{FIT_SESSION_FIELD_NUM_TOTAL_CYCLES, "TOTAL_CYCLES"},
	{FIT_SESSION_FIELD_NUM_NEC_LAT, "NEC_LAT"},
	{FIT_SESSION_FIELD_NUM_NEC_LONG, "NEC_LONG"},
	{FIT_SESSION_FIELD_NUM_SWC_LAT, "SWC_LAT"},
	{FIT_SESSION_FIELD_NUM_SWC_LONG, "SWC_LONG"},
	{FIT_SESSION_FIELD_NUM_END_POSITION_LAT, "END_POSITION_LAT"},
	{FIT_SESSION_FIELD_NUM_END_POSITION_LONG, "END_POSITION_LONG"},
	{FIT_SESSION_FIELD_NUM_AVG_STROKE_COUNT, "FIT_SESSION_FIELD_NUM_AVG_STROKE_COUNT"},
	{FIT_SESSION_FIELD_NUM_TOTAL_WORK, "TOTAL_WORK"},
	{FIT_SESSION_FIELD_NUM_TOTAL_MOVING_TIME, "TOTAL_MOVING_TIME"},
	{FIT_SESSION_FIELD_NUM_TIME_IN_HR_ZONE, "TIME_IN_HR_ZONE"},
	{FIT_SESSION_FIELD_NUM_TIME_IN_SPEED_ZONE, "TIME_IN_SPEED_ZONE"},
	{FIT_SESSION_FIELD_NUM_TIME_IN_CADENCE_ZONE, "TIME_IN_CADENCE_ZONE"},
	{FIT_SESSION_FIELD_NUM_TIME_IN_POWER_ZONE, "TIME_IN_POWER_ZONE"},
	{FIT_SESSION_FIELD_NUM_AVG_LAP_TIME, "AVG_LAP_TIME"},
	{FIT_SESSION_FIELD_NUM_SPORT_PROFILE_NAME, "SPORT_PROFILE_NAME"},
	{FIT_SESSION_FIELD_NUM_ENHANCED_AVG_SPEED, "ENHANCED_AVG_SPEED"},
	{FIT_SESSION_FIELD_NUM_ENHANCED_MAX_SPEED, "ENHANCED_MAX_SPEED"},
	{FIT_SESSION_FIELD_NUM_ENHANCED_AVG_ALTITUDE, "ENHANCED_AVG_ALTITUDE"},
	{FIT_SESSION_FIELD_NUM_ENHANCED_MIN_ALTITUDE, "ENHANCED_MIN_ALTITUDE"},
	{FIT_SESSION_FIELD_NUM_ENHANCED_MAX_ALTITUDE, "ENHANCED_MAX_ALTITUDE"},
	{FIT_SESSION_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SESSION_FIELD_NUM_TOTAL_FAT_CALORIES, "TOTAL_FAT_CALORIES"},
	{FIT_SESSION_FIELD_NUM_AVG_SPEED, "AVG_SPEED"},
	{FIT_SESSION_FIELD_NUM_MAX_SPEED, "MAX_SPEED"},
	{FIT_SESSION_FIELD_NUM_AVG_POWER, "AVG_POWER"},
	{FIT_SESSION_FIELD_NUM_MAX_POWER, "MAX_POWER"},
	{FIT_SESSION_FIELD_NUM_TOTAL_ASCENT, "TOTAL_ASCENT"},
	{FIT_SESSION_FIELD_NUM_TOTAL_DESCENT, "TOTAL_DESCENT"},
	{FIT_SESSION_FIELD_NUM_FIRST_LAP_INDEX, "FIRST_LAP_INDEX"},
	{FIT_SESSION_FIELD_NUM_NUM_LAPS, "NUM_LAPS"},
	{FIT_SESSION_FIELD_NUM_NUM_LENGTHS, "NUM_LENGTHS"},
	{FIT_SESSION_FIELD_NUM_NORMALIZED_POWER, "NORMALIZED_POWER"},
	{FIT_SESSION_FIELD_NUM_TRAINING_STRESS_SCORE, "TRAINING_STRESS_SCORE"},
	{FIT_SESSION_FIELD_NUM_INTENSITY_FACTOR, "INTENSITY_FACTOR"},
	{FIT_SESSION_FIELD_NUM_LEFT_RIGHT_BALANCE, "LEFT_RIGHT_BALANCE"},
	{FIT_SESSION_FIELD_NUM_AVG_STROKE_DISTANCE, "AVG_STROKE_DISTANCE"},
	{FIT_SESSION_FIELD_NUM_POOL_LENGTH, "POOL_LENGTH"},
	{FIT_SESSION_FIELD_NUM_THRESHOLD_POWER, "THRESHOLD_POWER"},
	{FIT_SESSION_FIELD_NUM_NUM_ACTIVE_LENGTHS, "NUM_ACTIVE_LENGTHS"},
	{FIT_SESSION_FIELD_NUM_AVG_ALTITUDE, "AVG_ALTITUDE"},
	{FIT_SESSION_FIELD_NUM_MAX_ALTITUDE, "MAX_ALTITUDE"},
	{FIT_SESSION_FIELD_NUM_AVG_GRADE, "AVG_GRADE"},
	{FIT_SESSION_FIELD_NUM_AVG_POS_GRADE, "AVG_POS_GRADE"},
	{FIT_SESSION_FIELD_NUM_AVG_NEG_GRADE, "AVG_NEG_GRADE"},
	{FIT_SESSION_FIELD_NUM_MAX_POS_GRADE, "MAX_POS_GRADE"},
	{FIT_SESSION_FIELD_NUM_MAX_NEG_GRADE, "MAX_NEG_GRADE"},
	{FIT_SESSION_FIELD_NUM_AVG_POS_VERTICAL_SPEED, "AVG_POS_VERTICAL_SPEED"},
	{FIT_SESSION_FIELD_NUM_AVG_NEG_VERTICAL_SPEED, "AVG_NEG_VERTICAL_SPEED"},
	{FIT_SESSION_FIELD_NUM_MAX_POS_VERTICAL_SPEED, "MAX_POS_VERTICAL_SPEED"},
	{FIT_SESSION_FIELD_NUM_MAX_NEG_VERTICAL_SPEED, "MAX_NEG_VERTICAL_SPEED"},
	{FIT_SESSION_FIELD_NUM_BEST_LAP_INDEX, "BEST_LAP_INDEX"},
	{FIT_SESSION_FIELD_NUM_MIN_ALTITUDE, "MIN_ALTITUDE"},
	{FIT_SESSION_FIELD_NUM_PLAYER_SCORE, "PLAYER_SCORE"},
	{FIT_SESSION_FIELD_NUM_OPPONENT_SCORE, "OPPONENT_SCORE"},
	{FIT_SESSION_FIELD_NUM_STROKE_COUNT, "STROKE_COUNT"},
	{FIT_SESSION_FIELD_NUM_ZONE_COUNT, "ZONE_COUNT"},
	{FIT_SESSION_FIELD_NUM_MAX_BALL_SPEED, "MAX_BALL_SPEED"},
	{FIT_SESSION_FIELD_NUM_AVG_BALL_SPEED, "AVG_BALL_SPEED"},
	{FIT_SESSION_FIELD_NUM_AVG_VERTICAL_OSCILLATION, "AVG_VERTICAL_OSCILLATION"},
	{FIT_SESSION_FIELD_NUM_AVG_STANCE_TIME_PERCENT, "AVG_STANCE_TIME_PERCENT"},
	{FIT_SESSION_FIELD_NUM_AVG_STANCE_TIME, "AVG_STANCE_TIME"},
	{FIT_SESSION_FIELD_NUM_AVG_VAM, "AVG_VAM"},
	{FIT_SESSION_FIELD_NUM_EVENT, "EVENT"},
	{FIT_SESSION_FIELD_NUM_EVENT_TYPE, "EVENT_TYPE"},
	{FIT_SESSION_FIELD_NUM_SPORT, "SPORT"},
	{FIT_SESSION_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_SESSION_FIELD_NUM_AVG_HEART_RATE, "AVG_HEART_RATE"},
	{FIT_SESSION_FIELD_NUM_MAX_HEART_RATE, "MAX_HEART_RATE"},
	{FIT_SESSION_FIELD_NUM_AVG_CADENCE, "AVG_CADENCE"},
	{FIT_SESSION_FIELD_NUM_MAX_CADENCE, "MAX_CADENCE"},
	{FIT_SESSION_FIELD_NUM_TOTAL_TRAINING_EFFECT, "TOTAL_TRAINING_EFFECT"},
	{FIT_SESSION_FIELD_NUM_EVENT_GROUP, "EVENT_GROUP"},
	{FIT_SESSION_FIELD_NUM_TRIGGER, "TRIGGER"},
	{FIT_SESSION_FIELD_NUM_SWIM_STROKE, "SWIM_STROKE"},
	{FIT_SESSION_FIELD_NUM_POOL_LENGTH_UNIT, "POOL_LENGTH_UNIT"},
	{FIT_SESSION_FIELD_NUM_GPS_ACCURACY, "GPS_ACCURACY"},
	{FIT_SESSION_FIELD_NUM_AVG_TEMPERATURE, "AVG_TEMPERATURE"},
	{FIT_SESSION_FIELD_NUM_MAX_TEMPERATURE, "MAX_TEMPERATURE"},
	{FIT_SESSION_FIELD_NUM_MIN_HEART_RATE, "MIN_HEART_RATE"},
	{FIT_SESSION_FIELD_NUM_OPPONENT_NAME, "OPPONENT_NAME"},
	{FIT_SESSION_FIELD_NUM_AVG_FRACTIONAL_CADENCE, "AVG_FRACTIONAL_CADENCE"},
	{FIT_SESSION_FIELD_NUM_MAX_FRACTIONAL_CADENCE, "MAX_FRACTIONAL_CADENCE"},
	{FIT_SESSION_FIELD_NUM_TOTAL_FRACTIONAL_CYCLES, "TOTAL_FRACTIONAL_CYCLES"},
	{FIT_SESSION_FIELD_NUM_SPORT_INDEX, "SPORT_INDEX"},
	{FIT_SESSION_FIELD_NUM_TOTAL_ANAEROBIC_TRAINING_EFFECT, "TOTAL_ANAEROBIC_TRAINING_EFFECT"},
	{FIT_SESSION_FIELD_NUM_MIN_TEMPERATURE, "MIN_TEMPERATURE"}
};

static _field_title lap_mesg[FIT_LAP_MESG_FIELDS] = {
	{FIT_LAP_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_LAP_FIELD_NUM_START_TIME, "START_TIME"},
	{FIT_LAP_FIELD_NUM_START_POSITION_LAT, "START_POSITION_LAT"},
	{FIT_LAP_FIELD_NUM_START_POSITION_LONG, "START_POSITION_LONG"},
	{FIT_LAP_FIELD_NUM_END_POSITION_LAT, "END_POSITION_LAT"},
	{FIT_LAP_FIELD_NUM_END_POSITION_LONG, "END_POSITION_LONG"},
	{FIT_LAP_FIELD_NUM_TOTAL_ELAPSED_TIME, "TOTAL_ELAPSED_TIME"},
	{FIT_LAP_FIELD_NUM_TOTAL_TIMER_TIME, "TOTAL_TIMER_TIME"},
	{FIT_LAP_FIELD_NUM_TOTAL_DISTANCE, "TOTAL_DISTANCE"},
	{FIT_LAP_FIELD_NUM_TOTAL_CYCLES, "TOTAL_CYCLES"},
	{FIT_LAP_FIELD_NUM_TOTAL_WORK, "TOTAL_WORK"},
	{FIT_LAP_FIELD_NUM_TOTAL_MOVING_TIME, "TOTAL_MOVING_TIME"},
	{FIT_LAP_FIELD_NUM_TIME_IN_HR_ZONE, "TIME_IN_HR_ZONE"},
	{FIT_LAP_FIELD_NUM_TIME_IN_SPEED_ZONE, "TIME_IN_SPEED_ZONE"},
	{FIT_LAP_FIELD_NUM_TIME_IN_CADENCE_ZONE, "TIME_IN_CADENCE_ZONE"},
	{FIT_LAP_FIELD_NUM_TIME_IN_POWER_ZONE, "TIME_IN_POWER_ZONE"},
	{FIT_LAP_FIELD_NUM_ENHANCED_AVG_SPEED, "ENHANCED_AVG_SPEED"},
	{FIT_LAP_FIELD_NUM_ENHANCED_MAX_SPEED, "ENHANCED_MAX_SPEED"},
	{FIT_LAP_FIELD_NUM_ENHANCED_AVG_ALTITUDE, "ENHANCED_AVG_ALTITUDE"},
	{FIT_LAP_FIELD_NUM_ENHANCED_MIN_ALTITUDE, "ENHANCED_MIN_ALTITUDE"},
	{FIT_LAP_FIELD_NUM_ENHANCED_MAX_ALTITUDE, "ENHANCED_MAX_ALTITUDE"},
	{FIT_LAP_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_LAP_FIELD_NUM_TOTAL_CALORIES, "TOTAL_CALORIES"},
	{FIT_LAP_FIELD_NUM_TOTAL_FAT_CALORIES, "TOTAL_FAT_CALORIES"},
	{FIT_LAP_FIELD_NUM_AVG_SPEED, "AVG_SPEED"},
	{FIT_LAP_FIELD_NUM_MAX_SPEED, "MAX_SPEED"},
	{FIT_LAP_FIELD_NUM_AVG_POWER, "AVG_POWER"},
	{FIT_LAP_FIELD_NUM_MAX_POWER, "MAX_POWER"},
	{FIT_LAP_FIELD_NUM_TOTAL_ASCENT, "TOTAL_ASCENT"},
	{FIT_LAP_FIELD_NUM_TOTAL_DESCENT, "TOTAL_DESCENT"},
	{FIT_LAP_FIELD_NUM_NUM_LENGTHS, "NUM_LENGTHS"},
	{FIT_LAP_FIELD_NUM_NORMALIZED_POWER, "NORMALIZED_POWER"},
	{FIT_LAP_FIELD_NUM_LEFT_RIGHT_BALANCE, "LEFT_RIGHT_BALANCE"},
	{FIT_LAP_FIELD_NUM_FIRST_LENGTH_INDEX, "FIRST_LENGTH_INDEX"},
	{FIT_LAP_FIELD_NUM_AVG_STROKE_DISTANCE, "AVG_STROKE_DISTANCE"},
	{FIT_LAP_FIELD_NUM_NUM_ACTIVE_LENGTHS, "NUM_ACTIVE_LENGTHS"},
	{FIT_LAP_FIELD_NUM_AVG_ALTITUDE, "AVG_ALTITUDE"},
	{FIT_LAP_FIELD_NUM_MAX_ALTITUDE, "MAX_ALTITUDE"},
	{FIT_LAP_FIELD_NUM_AVG_GRADE, "AVG_GRADE"},
	{FIT_LAP_FIELD_NUM_AVG_POS_GRADE, "AVG_POS_GRADE"},
	{FIT_LAP_FIELD_NUM_AVG_NEG_GRADE, "AVG_NEG_GRADE"},
	{FIT_LAP_FIELD_NUM_MAX_POS_GRADE, "MAX_POS_GRADE"},
	{FIT_LAP_FIELD_NUM_MAX_NEG_GRADE, "MAX_NEG_GRADE"},
	{FIT_LAP_FIELD_NUM_AVG_POS_VERTICAL_SPEED, "AVG_POS_VERTICAL_SPEED"},
	{FIT_LAP_FIELD_NUM_AVG_NEG_VERTICAL_SPEED, "AVG_NEG_VERTICAL_SPEED"},
	{FIT_LAP_FIELD_NUM_MAX_POS_VERTICAL_SPEED, "MAX_POS_VERTICAL_SPEED"},
	{FIT_LAP_FIELD_NUM_MAX_NEG_VERTICAL_SPEED, "MAX_NEG_VERTICAL_SPEED"},
	{FIT_LAP_FIELD_NUM_REPETITION_NUM, "REPETITION_NUM"},
	{FIT_LAP_FIELD_NUM_MIN_ALTITUDE, "MIN_ALTITUDE"},
	{FIT_LAP_FIELD_NUM_WKT_STEP_INDEX, "WKT_STEP_INDEX"},
	{FIT_LAP_FIELD_NUM_OPPONENT_SCORE, "OPPONENT_SCORE"},
	{FIT_LAP_FIELD_NUM_STROKE_COUNT, "STROKE_COUNT"},
	{FIT_LAP_FIELD_NUM_ZONE_COUNT, "ZONE_COUNT"},
	{FIT_LAP_FIELD_NUM_AVG_VERTICAL_OSCILLATION, "AVG_VERTICAL_OSCILLATION"},
	{FIT_LAP_FIELD_NUM_AVG_STANCE_TIME_PERCENT, "AVG_STANCE_TIME_PERCENT"},
	{FIT_LAP_FIELD_NUM_AVG_STANCE_TIME, "AVG_STANCE_TIME"},
	{FIT_LAP_FIELD_NUM_PLAYER_SCORE, "PLAYER_SCORE"},
	{FIT_LAP_FIELD_NUM_AVG_TOTAL_HEMOGLOBIN_CONC, "AVG_TOTAL_HEMOGLOBIN_CONC"},
	{FIT_LAP_FIELD_NUM_MIN_TOTAL_HEMOGLOBIN_CONC, "MIN_TOTAL_HEMOGLOBIN_CONC"},
	{FIT_LAP_FIELD_NUM_MAX_TOTAL_HEMOGLOBIN_CONC, "MAX_TOTAL_HEMOGLOBIN_CONC"},
	{FIT_LAP_FIELD_NUM_AVG_SATURATED_HEMOGLOBIN_PERCENT, "AVG_SATURATED_HEMOGLOBIN_PERCENT"},
	{FIT_LAP_FIELD_NUM_MIN_SATURATED_HEMOGLOBIN_PERCENT, "MIN_SATURATED_HEMOGLOBIN_PERCENT"},
	{FIT_LAP_FIELD_NUM_MAX_SATURATED_HEMOGLOBIN_PERCENT, "MAX_SATURATED_HEMOGLOBIN_PERCENT"},
	{FIT_LAP_FIELD_NUM_AVG_VAM, "AVG_VAM"},
	{FIT_LAP_FIELD_NUM_EVENT, "EVENT"},
	{FIT_LAP_FIELD_NUM_EVENT_TYPE, "EVENT_TYPE"},
	{FIT_LAP_FIELD_NUM_AVG_HEART_RATE, "AVG_HEART_RATE"},
	{FIT_LAP_FIELD_NUM_MAX_HEART_RATE, "MAX_HEART_RATE"},
	{FIT_LAP_FIELD_NUM_AVG_CADENCE, "AVG_CADENCE"},
	{FIT_LAP_FIELD_NUM_MAX_CADENCE, "MAX_CADENCE"},
	{FIT_LAP_FIELD_NUM_INTENSITY, "INTENSITY"},
	{FIT_LAP_FIELD_NUM_LAP_TRIGGER, "LAP_TRIGGER"},
	{FIT_LAP_FIELD_NUM_SPORT, "SPORT"},
	{FIT_LAP_FIELD_NUM_EVENT_GROUP, "EVENT_GROUP"},
	{FIT_LAP_FIELD_NUM_SWIM_STROKE, "SWIM_STROKE"},
	{FIT_LAP_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_LAP_FIELD_NUM_GPS_ACCURACY, "GPS_ACCURACY"},
	{FIT_LAP_FIELD_NUM_AVG_TEMPERATURE, "AVG_TEMPERATURE"},
	{FIT_LAP_FIELD_NUM_MAX_TEMPERATURE, "MAX_TEMPERATURE"},
	{FIT_LAP_FIELD_NUM_MIN_HEART_RATE, "MIN_HEART_RATE"},
	{FIT_LAP_FIELD_NUM_AVG_FRACTIONAL_CADENCE, "AVG_FRACTIONAL_CADENCE"},
	{FIT_LAP_FIELD_NUM_MAX_FRACTIONAL_CADENCE, "MAX_FRACTIONAL_CADENCE"},
	{FIT_LAP_FIELD_NUM_TOTAL_FRACTIONAL_CYCLES, "TOTAL_FRACTIONAL_CYCLES"},
	{FIT_LAP_FIELD_NUM_MIN_TEMPERATURE, "MIN_TEMPERATURE"}
};

static _field_title length_mesg[FIT_LENGTH_MESG_FIELDS] = {
	{FIT_LENGTH_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_LENGTH_FIELD_NUM_START_TIME, "START_TIME"},
	{FIT_LENGTH_FIELD_NUM_TOTAL_ELAPSED_TIME, "TOTAL_ELAPSED_TIME"},
	{FIT_LENGTH_FIELD_NUM_TOTAL_TIMER_TIME, "TOTAL_TIMER_TIME"},
	{FIT_LENGTH_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_LENGTH_FIELD_NUM_TOTAL_STROKES, "TOTAL_STROKES"},
	{FIT_LENGTH_FIELD_NUM_AVG_SPEED, "AVG_SPEED"},
	{FIT_LENGTH_FIELD_NUM_TOTAL_CALORIES, "TOTAL_CALORIES"},
	{FIT_LENGTH_FIELD_NUM_PLAYER_SCORE, "PLAYER_SCORE"},
	{FIT_LENGTH_FIELD_NUM_OPPONENT_SCORE, "OPPONENT_SCORE"},
	{FIT_LENGTH_FIELD_NUM_STROKE_COUNT, "STROKE_COUNT"},
	{FIT_LENGTH_FIELD_NUM_ZONE_COUNT, "ZONE_COUNT"},
	{FIT_LENGTH_FIELD_NUM_EVENT, "EVENT"},
	{FIT_LENGTH_FIELD_NUM_EVENT_TYPE, "EVENT_TYPE"},
	{FIT_LENGTH_FIELD_NUM_SWIM_STROKE, "SWIM_STROKE"},
	{FIT_LENGTH_FIELD_NUM_AVG_SWIMMING_CADENCE, "AVG_SWIMMING_CADENCE"},
	{FIT_LENGTH_FIELD_NUM_EVENT_GROUP, "EVENT_GROUP"},
	{FIT_LENGTH_FIELD_NUM_LENGTH_TYPE, "LENGTH_TYPE"}
};

static _field_title record_mesg[FIT_RECORD_MESG_FIELDS] = {
	{FIT_RECORD_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_RECORD_FIELD_NUM_POSITION_LAT, "POSITION_LAT"},
	{FIT_RECORD_FIELD_NUM_POSITION_LONG, "POSITION_LONG"},
	{FIT_RECORD_FIELD_NUM_DISTANCE, "DISTANCE"},
	{FIT_RECORD_FIELD_NUM_TIME_FROM_COURSE, "TIME_FROM_COURSE"},
	{FIT_RECORD_FIELD_NUM_TOTAL_CYCLES, "TOTAL_CYCLES"},
	{FIT_RECORD_FIELD_NUM_ACCUMULATED_POWER, "ACCUMULATED_POWER"},
	{FIT_RECORD_FIELD_NUM_ENHANCED_SPEED, "ENHANCED_SPEED"},
	{FIT_RECORD_FIELD_NUM_ENHANCED_ALTITUDE, "ENHANCED_ALTITUDE"},
	{FIT_RECORD_FIELD_NUM_ALTITUDE, "ALTITUDE"},
	{FIT_RECORD_FIELD_NUM_SPEED, "SPEED"},
	{FIT_RECORD_FIELD_NUM_POWER, "POWER"},
	{FIT_RECORD_FIELD_NUM_GRADE, "GRADE"},
	{FIT_RECORD_FIELD_NUM_COMPRESSED_ACCUMULATED_POWER, "COMPRESSED_ACCUMULATED_POWER"},
	{FIT_RECORD_FIELD_NUM_VERTICAL_SPEED, "VERTICAL_SPEED"},
	{FIT_RECORD_FIELD_NUM_CALORIES, "CALORIES"},
	{FIT_RECORD_FIELD_NUM_VERTICAL_OSCILLATION, "VERTICAL_OSCILLATION"},
	{FIT_RECORD_FIELD_NUM_STANCE_TIME_PERCENT, "STANCE_TIME_PERCENT"},
	{FIT_RECORD_FIELD_NUM_STANCE_TIME, "STANCE_TIME"},
	{FIT_RECORD_FIELD_NUM_BALL_SPEED, "BALL_SPEED"},
	{FIT_RECORD_FIELD_NUM_CADENCE256, "CADENCE256"},
	{FIT_RECORD_FIELD_NUM_TOTAL_HEMOGLOBIN_CONC, "TOTAL_HEMOGLOBIN_CONC"},
	{FIT_RECORD_FIELD_NUM_TOTAL_HEMOGLOBIN_CONC_MIN, "TOTAL_HEMOGLOBIN_CONC_MIN"},
	{FIT_RECORD_FIELD_NUM_TOTAL_HEMOGLOBIN_CONC_MAX, "TOTAL_HEMOGLOBIN_CONC_MAX"},
	{FIT_RECORD_FIELD_NUM_SATURATED_HEMOGLOBIN_PERCENT, "SATURATED_HEMOGLOBIN_PERCENT"},
	{FIT_RECORD_FIELD_NUM_SATURATED_HEMOGLOBIN_PERCENT_MIN, "SATURATED_HEMOGLOBIN_PERCENT_MIN"},
	{FIT_RECORD_FIELD_NUM_SATURATED_HEMOGLOBIN_PERCENT_MAX, "SATURATED_HEMOGLOBIN_PERCENT_MAX"},
	{FIT_RECORD_FIELD_NUM_HEART_RATE, "HEART_RATE"},
	{FIT_RECORD_FIELD_NUM_CADENCE, "CADENCE"},
	{FIT_RECORD_FIELD_NUM_COMPRESSED_SPEED_DISTANCE, "COMPRESSED_SPEED_DISTANCE"},
	{FIT_RECORD_FIELD_NUM_RESISTANCE, "RESISTANCE"},
	{FIT_RECORD_FIELD_NUM_TEMPERATURE, "TEMPERATURE,"},
	{FIT_RECORD_FIELD_NUM_SPEED_1S, "SPEED_1S"},
	{FIT_RECORD_FIELD_NUM_CYCLES, "CYCLES"},
	{FIT_RECORD_FIELD_NUM_LEFT_RIGHT_BALANCE, "LEFT_RIGHT_BALANCE"},
	{FIT_RECORD_FIELD_NUM_GPS_ACCURACY, "GPS_ACCURACY"},
	{FIT_RECORD_FIELD_NUM_ACTIVITY_TYPE, "ACTIVITY_TYPE"},
	{FIT_RECORD_FIELD_NUM_LEFT_TORQUE_EFFECTIVENESS, "LEFT_TORQUE_EFFECTIVENESS"},
	{FIT_RECORD_FIELD_NUM_RIGHT_TORQUE_EFFECTIVENESS, "RIGHT_TORQUE_EFFECTIVENESS"},
	{FIT_RECORD_FIELD_NUM_LEFT_PEDAL_SMOOTHNESS, "LEFT_PEDAL_SMOOTHNESS"},
	{FIT_RECORD_FIELD_NUM_RIGHT_PEDAL_SMOOTHNESS, "RIGHT_PEDAL_SMOOTHNESS"},
	{FIT_RECORD_FIELD_NUM_COMBINED_PEDAL_SMOOTHNESS, "COMBINED_PEDAL_SMOOTHNESS"},
	{FIT_RECORD_FIELD_NUM_TIME128, "TIME128"},
	{FIT_RECORD_FIELD_NUM_STROKE_TYPE, "STROKE_TYPE"},
	{FIT_RECORD_FIELD_NUM_ZONE, "ZONE"},
	{FIT_RECORD_FIELD_NUM_FRACTIONAL_CADENCE, "FRACTIONAL_CADENCE"},
	{FIT_RECORD_FIELD_NUM_DEVICE_INDEX, "DEVICE_INDEX"}
};

static _field_title event_mesg[FIT_EVENT_MESG_FIELDS] = {
	{FIT_EVENT_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_EVENT_FIELD_NUM_DATA, "DATA"},
	{FIT_EVENT_FIELD_NUM_DATA16, "DATA16"},
	{FIT_EVENT_FIELD_NUM_SCORE, "SCORE"},
	{FIT_EVENT_FIELD_NUM_OPPONENT_SCORE, "OPPONENT_SCORE"},
	{FIT_EVENT_FIELD_NUM_EVENT, "EVENT"},
	{FIT_EVENT_FIELD_NUM_EVENT_TYPE, "EVENT_TYPE"},
	{FIT_EVENT_FIELD_NUM_EVENT_GROUP, "EVENT_GROUP"},
	{FIT_EVENT_FIELD_NUM_FRONT_GEAR_NUM, "FRONT_GEAR_NUM"},
	{FIT_EVENT_FIELD_NUM_FRONT_GEAR, "FRONT_GEAR"},
	{FIT_EVENT_FIELD_NUM_REAR_GEAR_NUM, "REAR_GEAR_NUM"},
	{FIT_EVENT_FIELD_NUM_REAR_GEAR, "REAR_GEAR"},
	{FIT_EVENT_FIELD_NUM_RADAR_THREAT_LEVEL_MAX, "RADAR_THREAT_LEVEL_MAX"},
	{FIT_EVENT_FIELD_NUM_RADAR_THREAT_COUNT, "RADAR_THREAT_COUNT"}
};

static _field_title device_info_mesg[FIT_DEVICE_INFO_MESG_FIELDS] = {
	{FIT_DEVICE_INFO_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_DEVICE_INFO_FIELD_NUM_SERIAL_NUMBER, "SERIAL_NUMBER"},
	{FIT_DEVICE_INFO_FIELD_NUM_CUM_OPERATING_TIME, "CUM_OPERATING_TIME"},
	{FIT_DEVICE_INFO_FIELD_NUM_PRODUCT_NAME, "PRODUCT_NAME"},
	{FIT_DEVICE_INFO_FIELD_NUM_MANUFACTURER, "MANUFACTURER"},
	{FIT_DEVICE_INFO_FIELD_NUM_PRODUCT, "PRODUCT"},
	{FIT_DEVICE_INFO_FIELD_NUM_SOFTWARE_VERSION, "SOFTWARE_VERSION"},
	{FIT_DEVICE_INFO_FIELD_NUM_BATTERY_VOLTAGE, "BATTERY_VOLTAGE"},
	{FIT_DEVICE_INFO_FIELD_NUM_ANT_DEVICE_NUMBER, "ANT_DEVICE_NUMBER"},
	{FIT_DEVICE_INFO_FIELD_NUM_DEVICE_INDEX, "DEVICE_INDEX"},
	{FIT_DEVICE_INFO_FIELD_NUM_DEVICE_TYPE, "DEVICE_TYPE"},
	{FIT_DEVICE_INFO_FIELD_NUM_HARDWARE_VERSION, "HARDWARE_VERSION"},
	{FIT_DEVICE_INFO_FIELD_NUM_BATTERY_STATUS, "BATTERY_STATUS"},
	{FIT_DEVICE_INFO_FIELD_NUM_SENSOR_POSITION, "SENSOR_POSITION"},
	{FIT_DEVICE_INFO_FIELD_NUM_DESCRIPTOR, "DESCRIPTOR"},
	{FIT_DEVICE_INFO_FIELD_NUM_ANT_TRANSMISSION_TYPE, "ANT_TRANSMISSION_TYPE"},
	{FIT_DEVICE_INFO_FIELD_NUM_ANT_NETWORK, "ANT_NETWORK"},
	{FIT_DEVICE_INFO_FIELD_NUM_SOURCE_TYPE, "SOURCE_TYPE"}
};

static _field_title device_aux_battery_info_mesg[FIT_DEVICE_AUX_BATTERY_INFO_MESG_FIELDS] = {
	{FIT_DEVICE_AUX_BATTERY_INFO_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_DEVICE_AUX_BATTERY_INFO_FIELD_NUM_BATTERY_VOLTAGE, "BATTERY_VOLTAGE"},
	{FIT_DEVICE_AUX_BATTERY_INFO_FIELD_NUM_DEVICE_INDEX, "DEVICE_INDEX"},
	{FIT_DEVICE_AUX_BATTERY_INFO_FIELD_NUM_BATTERY_STATUS, "BATTERY_STATUS"},
	{FIT_DEVICE_AUX_BATTERY_INFO_FIELD_NUM_BATTERY_IDENTIFIER, "BATTERY_IDENTIFIER"}
};

static _field_title training_file_mesg[FIT_TRAINING_FILE_MESG_FIELDS] = {
	{FIT_TRAINING_FILE_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_TRAINING_FILE_FIELD_NUM_SERIAL_NUMBER, "SERIAL_NUMBER"},
	{FIT_TRAINING_FILE_FIELD_NUM_TIME_CREATED, "TIME_CREATED"},
	{FIT_TRAINING_FILE_FIELD_NUM_MANUFACTURER, "MANUFACTURER"},
	{FIT_TRAINING_FILE_FIELD_NUM_PRODUCT, "PRODUCT"},
	{FIT_TRAINING_FILE_FIELD_NUM_TYPE, "TYPE"}
};

static _field_title weather_conditions_mesg[FIT_WEATHER_CONDITIONS_MESG_FIELDS] = {
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_LOCATION, "LOCATION"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_OBSERVED_AT_TIME, "OBSERVED_AT_TIME"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_OBSERVED_LOCATION_LAT, "OBSERVED_LOCATION_LAT"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_OBSERVED_LOCATION_LONG, "OBSERVED_LOCATION_LONG"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_WIND_DIRECTION, "WIND_DIRECTION"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_WIND_SPEED, "WIND_SPEED"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_WEATHER_REPORT, "WEATHER_REPORT"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_TEMPERATURE, "TEMPERATURE"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_CONDITION, "CONDITION"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_PRECIPITATION_PROBABILITY, "PRECIPITATION_PROBABILITY"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_TEMPERATURE_FEELS_LIKE, "TEMPERATURE_FEELS_LIKE"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_RELATIVE_HUMIDITY, "RELATIVE_HUMIDITY"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_DAY_OF_WEEK, "DAY_OF_WEEK"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_HIGH_TEMPERATURE, "HIGH_TEMPERATURE"},
	{FIT_WEATHER_CONDITIONS_FIELD_NUM_LOW_TEMPERATURE, "LOW_TEMPERATURE"}
};

static _field_title weather_alert_mesg[FIT_WEATHER_ALERT_MESG_FIELDS] = {
	{FIT_WEATHER_ALERT_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_WEATHER_ALERT_FIELD_NUM_REPORT_ID, "REPORT_ID"},
	{FIT_WEATHER_ALERT_FIELD_NUM_ISSUE_TIME, "ISSUE_TIME"},
	{FIT_WEATHER_ALERT_FIELD_NUM_EXPIRE_TIME, "EXPIRE_TIME"},
	{FIT_WEATHER_ALERT_FIELD_NUM_SEVERITY, "SEVERITY"},
	{FIT_WEATHER_ALERT_FIELD_NUM_TYPE, "TYPE"}
};

static _field_title nmea_sentence_mesg[FIT_NMEA_SENTENCE_MESG_FIELDS] = {
	{FIT_NMEA_SENTENCE_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_NMEA_SENTENCE_FIELD_NUM_TIMESTAMP_MS, "TIMESTAMP_MS"},
	{FIT_NMEA_SENTENCE_FIELD_NUM_SENTENCE, "SENTENCE"}
};

static _field_title aviation_attitude_mesg[FIT_AVIATION_ATTITUDE_MESG_FIELDS] = {
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_SYSTEM_TIME, "SYSTEM_TIME"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_TIMESTAMP_MS, "TIMESTAMP_MS"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_PITCH, "PITCH"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_ROLL, "ROLL"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_ACCEL_LATERAL, "ACCEL_LATERAL"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_ACCEL_NORMAL, "ACCEL_NORMAL"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_TURN_RATE, "TURN_RATE"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_TRACK, "TRACK"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_VALIDITY, "VALIDITY"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_STAGE, "STAGE"},
	{FIT_AVIATION_ATTITUDE_FIELD_NUM_ATTITUDE_STAGE_COMPLETE, "ATTITUDE_STAGE_COMPLETE"}
};

static _field_title video_title_mesg[FIT_VIDEO_TITLE_MESG_FIELDS] = {
	{FIT_VIDEO_TITLE_FIELD_NUM_TEXT, "TEXT"},
	{FIT_VIDEO_TITLE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_VIDEO_TITLE_FIELD_NUM_MESSAGE_COUNT, "MESSAGE_COUNT"}
};

static _field_title video_description_mesg[FIT_VIDEO_DESCRIPTION_MESG_FIELDS] = {
	{FIT_VIDEO_DESCRIPTION_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_VIDEO_DESCRIPTION_FIELD_NUM_MESSAGE_COUNT, "MESSAGE_COUNT"},
	{FIT_VIDEO_DESCRIPTION_FIELD_NUM_TEXT, "TEXT"}
};

static _field_title field_description_mesg[FIT_FIELD_DESCRIPTION_MESG_FIELDS] = {
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_FIELD_NAME, "FIELD_NAME"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_UNITS, "UNITS"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_FIT_BASE_UNIT_ID, "FIT_BASE_UNIT_ID"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_NATIVE_MESG_NUM, "NATIVE_MESG_NUM"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_DEVELOPER_DATA_INDEX, "DEVELOPER_DATA_INDEX"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_FIELD_DEFINITION_NUMBER, "FIELD_DEFINITION_NUMBER"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_FIT_BASE_TYPE_ID, "FIT_BASE_TYPE_ID"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_SCALE, "SCALE"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_OFFSET, "OFFSET"},
	{FIT_FIELD_DESCRIPTION_FIELD_NUM_NATIVE_FIELD_NUM, "NATIVE_FIELD_NUM"}
};

static _field_title developer_data_id_mesg[FIT_DEVELOPER_DATA_ID_MESG_FIELDS] = {
	{FIT_DEVELOPER_DATA_ID_FIELD_NUM_DEVELOPER_ID, "DEVELOPER_ID"},
	{FIT_DEVELOPER_DATA_ID_FIELD_NUM_APPLICATION_ID, "APPLICATION_ID"},
	{FIT_DEVELOPER_DATA_ID_FIELD_NUM_APPLICATION_VERSION, "APPLICATION_VERSION"},
	{FIT_DEVELOPER_DATA_ID_FIELD_NUM_MANUFACTURER_ID, "MANUFACTURER_ID"},
	{FIT_DEVELOPER_DATA_ID_FIELD_NUM_DEVELOPER_DATA_INDEX, "DEVELOPER_DATA_INDEX"}
};

static _field_title set_mesg[FIT_SET_MESG_FIELDS] = {
	{FIT_SET_FIELD_NUM_WEIGHT_DISPLAY_UNIT, "WEIGHT_DISPLAY_UNIT"}
};

static _field_title course_mesg[FIT_COURSE_MESG_FIELDS] = {
	{FIT_COURSE_FIELD_NUM_NAME, "NAME"},
	{FIT_COURSE_FIELD_NUM_CAPABILITIES, "CAPABILITIES"},
	{FIT_COURSE_FIELD_NUM_SPORT, "SPORT"},
	{FIT_COURSE_FIELD_NUM_SUB_SPORT, "SUB_SPORT"}
};

static _field_title course_point_mesg[FIT_COURSE_POINT_MESG_FIELDS] = {
	{FIT_COURSE_POINT_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_COURSE_POINT_FIELD_NUM_POSITION_LAT, "POSITION_LAT"},
	{FIT_COURSE_POINT_FIELD_NUM_POSITION_LONG, "POSITION_LONG"},
	{FIT_COURSE_POINT_FIELD_NUM_DISTANCE, "DISTANCE"},
	{FIT_COURSE_POINT_FIELD_NUM_NAME, "NAME"},
	{FIT_COURSE_POINT_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_COURSE_POINT_FIELD_NUM_TYPE, "TYPE"},
	{FIT_COURSE_POINT_FIELD_NUM_FAVORITE, "FAVORITE"}
};

static _field_title segment_id_mesg[FIT_SEGMENT_ID_MESG_FIELDS] = {
	{FIT_SEGMENT_ID_FIELD_NUM_USER_PROFILE_PRIMARY_KEY, "USER_PROFILE_PRIMARY_KEY"},
	{FIT_SEGMENT_ID_FIELD_NUM_DEVICE_ID, "DEVICE_ID"},
	{FIT_SEGMENT_ID_FIELD_NUM_NAME, "NAME"},
	{FIT_SEGMENT_ID_FIELD_NUM_UUID, "UUID"},
	{FIT_SEGMENT_ID_FIELD_NUM_SPORT, "SPORT"},
	{FIT_SEGMENT_ID_FIELD_NUM_ENABLED, "ENABLED"},
	{FIT_SEGMENT_ID_FIELD_NUM_DEFAULT_RACE_LEADER, "DEFAULT_RACE_LEADER"},
	{FIT_SEGMENT_ID_FIELD_NUM_DELETE_STATUS, "DELETE_STATUS"},
	{FIT_SEGMENT_ID_FIELD_NUM_SELECTION_TYPE, "SELECTION_TYPE"}
};

static _field_title segment_leaderboard_entry_mesg[FIT_SEGMENT_LEADERBOARD_ENTRY_MESG_FIELDS] = {
	{FIT_SEGMENT_LEADERBOARD_ENTRY_FIELD_NUM_GROUP_PRIMARY_KEY, "GROUP_PRIMARY_KEY"},
	{FIT_SEGMENT_LEADERBOARD_ENTRY_FIELD_NUM_ACTIVITY_ID, "ACTIVITY_ID"},
	{FIT_SEGMENT_LEADERBOARD_ENTRY_FIELD_NUM_SEGMENT_TIME, "SEGMENT_TIME"},
	{FIT_SEGMENT_LEADERBOARD_ENTRY_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SEGMENT_LEADERBOARD_ENTRY_FIELD_NUM_NAME, "NAME"},
	{FIT_SEGMENT_LEADERBOARD_ENTRY_FIELD_NUM_TYPE, "TYPE"}
};

static _field_title segment_point_mesg[FIT_SEGMENT_POINT_MESG_FIELDS] = {
	{FIT_SEGMENT_POINT_FIELD_NUM_POSITION_LAT, "POSITION_LAT"},
	{FIT_SEGMENT_POINT_FIELD_NUM_POSITION_LONG, "POSITION_LONG"},
	{FIT_SEGMENT_POINT_FIELD_NUM_DISTANCE, "DISTANCE"},
	{FIT_SEGMENT_POINT_FIELD_NUM_LEADER_TIME, "LEADER_TIME"},
	{FIT_SEGMENT_POINT_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SEGMENT_POINT_FIELD_NUM_ALTITUDE, "ALTITUDE"}
};

static _field_title segment_lap_mesg[FIT_SEGMENT_LAP_MESG_FIELDS] = {
	{FIT_SEGMENT_LAP_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_SEGMENT_LAP_FIELD_NUM_START_TIME, "START_TIME"},
	{FIT_SEGMENT_LAP_FIELD_NUM_START_POSITION_LAT, "START_POSITION_LAT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_START_POSITION_LONG, "START_POSITION_LONG"},
	{FIT_SEGMENT_LAP_FIELD_NUM_END_POSITION_LAT, "END_POSITION_LAT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_END_POSITION_LONG, "POSITION_LONG"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_ELAPSED_TIME, "TOTAL_ELAPSED_TIME"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_TIMER_TIME, "TOTAL_TIMER_TIME"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_DISTANCE, "TOTAL_DISTANCE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_CYCLES, "TOTAL_CYCLES"},
	{FIT_SEGMENT_LAP_FIELD_NUM_NEC_LAT, "NEC_LAT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_NEC_LONG, "NEC_LONG"},
	{FIT_SEGMENT_LAP_FIELD_NUM_SWC_LAT, "SWC_LAT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_SWC_LONG, "SWC_LONG"},
	{FIT_SEGMENT_LAP_FIELD_NUM_NAME, "NAME"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_WORK, "TOTAL_WORK"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_MOVING_TIME, "TOTAL_MOVING_TIME"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TIME_IN_HR_ZONE, "TIME_IN_HR_ZONE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TIME_IN_SPEED_ZONE, "TIME_IN_SPEED_ZONE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TIME_IN_CADENCE_ZONE, "TIME_IN_CADENCE_ZONE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TIME_IN_POWER_ZONE, "TIME_IN_POWER_ZONE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_ACTIVE_TIME, "ACTIVE_TIME"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_CALORIES, "TOTAL_CALORIES"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_FAT_CALORIES, "TOTAL_FAT_CALORIES"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_SPEED, "AVG_SPEED"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_SPEED, "MAX_SPEED"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_POWER, "AVG_POWER"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_POWER, "MAX_POWER"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_ASCENT, "TOTAL_ASCENT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_DESCENT, "TOTAL_DESCENT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_NORMALIZED_POWER, "NORMALIZED_POWER"},
	{FIT_SEGMENT_LAP_FIELD_NUM_LEFT_RIGHT_BALANCE, "LEFT_RIGHT_BALANCE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_ALTITUDE, "AVG_ALTITUDE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_ALTITUDE, "MAX_ALTITUDE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_GRADE, "AVG_GRADE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_POS_GRADE, "AVG_POS_GRADE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_NEG_GRADE, "AVG_NEG_GRADE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_POS_GRADE, "MAX_POS_GRADE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_NEG_GRADE, "MAX_NEG_GRADE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_POS_VERTICAL_SPEED, "AVG_POS_VERTICAL_SPEED"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_NEG_VERTICAL_SPEED, "AVG_NEG_VERTICAL_SPEED"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_POS_VERTICAL_SPEED, "MAX_POS_VERTICAL_SPEED"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_NEG_VERTICAL_SPEED, "MAX_NEG_VERTICAL_SPEED"},
	{FIT_SEGMENT_LAP_FIELD_NUM_REPETITION_NUM, "REPETITION_NUM"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MIN_ALTITUDE, "MIN_ALTITUDE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_WKT_STEP_INDEX, "WKT_STEP_INDEX"},
	{FIT_SEGMENT_LAP_FIELD_NUM_FRONT_GEAR_SHIFT_COUNT, "FRONT_GEAR_SHIFT_COUNT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_REAR_GEAR_SHIFT_COUNT, "REAR_GEAR_SHIFT_COUNT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_EVENT, "EVENT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_EVENT_TYPE, "EVENT_TYPE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_HEART_RATE, "AVG_HEART_RATE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_HEART_RATE, "MAX_HEART_RATE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_CADENCE, "AVG_CADENCE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_CADENCE, "MAX_CADENCE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_SPORT, "SPORT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_EVENT_GROUP, "EVENT_GROUP"},
	{FIT_SEGMENT_LAP_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_GPS_ACCURACY, "GPS_ACCURACY"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_TEMPERATURE, "AVG_TEMPERATURE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_TEMPERATURE, "MAX_TEMPERATURE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MIN_HEART_RATE, "MIN_HEART_RATE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_SPORT_EVENT, "SPORT_EVENT"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_LEFT_TORQUE_EFFECTIVENESS, "AVG_LEFT_TORQUE_EFFECTIVENESS"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_RIGHT_TORQUE_EFFECTIVENESS, "AVG_RIGHT_TORQUE_EFFECTIVENESS"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_LEFT_PEDAL_SMOOTHNESS, "AVG_LEFT_PEDAL_SMOOTHNESS"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_RIGHT_PEDAL_SMOOTHNESS, "AVG_RIGHT_PEDAL_SMOOTHNESS"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_COMBINED_PEDAL_SMOOTHNESS, "AVG_COMBINED_PEDAL_SMOOTHNESS"},
	{FIT_SEGMENT_LAP_FIELD_NUM_STATUS, "STATUS"},
	{FIT_SEGMENT_LAP_FIELD_NUM_UUID, "UUID"},
	{FIT_SEGMENT_LAP_FIELD_NUM_AVG_FRACTIONAL_CADENCE, "AVG_FRACTIONAL_CADENCE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_MAX_FRACTIONAL_CADENCE, "MAX_FRACTIONAL_CADENCE"},
	{FIT_SEGMENT_LAP_FIELD_NUM_TOTAL_FRACTIONAL_CYCLES, "TOTAL_FRACTIONAL_CYCLES"}
};

static _field_title segment_file_mesg[FIT_SEGMENT_FILE_MESG_FIELDS] = {
	{FIT_SEGMENT_FILE_FIELD_NUM_USER_PROFILE_PRIMARY_KEY, "USER_PROFILE_PRIMARY_KEY"},
	{FIT_SEGMENT_FILE_FIELD_NUM_LEADER_GROUP_PRIMARY_KEY, "LEADER_GROUP_PRIMARY_KEY"},
	{FIT_SEGMENT_FILE_FIELD_NUM_LEADER_ACTIVITY_ID, "LEADER_ACTIVITY_ID"},
	{FIT_SEGMENT_FILE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_SEGMENT_FILE_FIELD_NUM_FILE_UUID, "FILE_UUID"},
	{FIT_SEGMENT_FILE_FIELD_NUM_ENABLED, "ENABLED"},
	{FIT_SEGMENT_FILE_FIELD_NUM_LEADER_TYPE, "LEADER_TYPE"}
};

static _field_title workout_mesg[FIT_WORKOUT_MESG_FIELDS] = {
	{FIT_WORKOUT_FIELD_NUM_CAPABILITIES, "CAPABILITIES"},
	{FIT_WORKOUT_FIELD_NUM_WKT_NAME, "WKT_NAME"},
	{FIT_WORKOUT_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_WORKOUT_FIELD_NUM_NUM_VALID_STEPS, "NUM_VALID_STEPS"},
	{FIT_WORKOUT_FIELD_NUM_POOL_LENGTH, "POOL_LENGTH"},
	{FIT_WORKOUT_FIELD_NUM_SPORT, "SPORT"},
	{FIT_WORKOUT_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_WORKOUT_FIELD_NUM_POOL_LENGTH_UNIT, "POOL_LENGTH_UNIT"}
};

static _field_title workout_session_mesg[FIT_WORKOUT_SESSION_MESG_FIELDS] = {
	{FIT_WORKOUT_SESSION_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_WORKOUT_SESSION_FIELD_NUM_NUM_VALID_STEPS, "NUM_VALID_STEPS"},
	{FIT_WORKOUT_SESSION_FIELD_NUM_FIRST_STEP_INDEX, "FIRST_STEP_INDEX"},
	{FIT_WORKOUT_SESSION_FIELD_NUM_POOL_LENGTH, "POOL_LENGTH"},
	{FIT_WORKOUT_SESSION_FIELD_NUM_SPORT, "SPORT"},
	{FIT_WORKOUT_SESSION_FIELD_NUM_SUB_SPORT, "SUB_SPORT"},
	{FIT_WORKOUT_SESSION_FIELD_NUM_POOL_LENGTH_UNIT, "POOL_LENGTH_UNIT"}
};

static _field_title workout_step_mesg[FIT_WORKOUT_STEP_MESG_FIELDS] = {
	{FIT_WORKOUT_STEP_FIELD_NUM_WKT_STEP_NAME, "WKT_STEP_NAME"},
	{FIT_WORKOUT_STEP_FIELD_NUM_DURATION_VALUE, "DURATION_VALUE"},
	{FIT_WORKOUT_STEP_FIELD_NUM_TARGET_VALUE, "TARGET_VALUE"},
	{FIT_WORKOUT_STEP_FIELD_NUM_CUSTOM_TARGET_VALUE_LOW, "CUSTOM_TARGET_VALUE_LOW"},
	{FIT_WORKOUT_STEP_FIELD_NUM_CUSTOM_TARGET_VALUE_HIGH, "CUSTOM_TARGET_VALUE_HIGH"},
	{FIT_WORKOUT_STEP_FIELD_NUM_SECONDARY_TARGET_VALUE, "SECONDARY_TARGET_VALUE"},
	{FIT_WORKOUT_STEP_FIELD_NUM_SECONDARY_CUSTOM_TARGET_VALUE_LOW, "SECONDARY_CUSTOM_TARGET_VALUE_LOW"},
	{FIT_WORKOUT_STEP_FIELD_NUM_SECONDARY_CUSTOM_TARGET_VALUE_HIGH, "SECONDARY_CUSTOM_TARGET_VALUE_HIGH"},
	{FIT_WORKOUT_STEP_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_WORKOUT_STEP_FIELD_NUM_EXERCISE_CATEGORY, "EXERCISE_CATEGORY"},
	{FIT_WORKOUT_STEP_FIELD_NUM_DURATION_TYPE, "DURATION_TYPE"},
	{FIT_WORKOUT_STEP_FIELD_NUM_TARGET_TYPE, "TARGET_TYPE"},
	{FIT_WORKOUT_STEP_FIELD_NUM_INTENSITY, "INTENSITY"},
	{FIT_WORKOUT_STEP_FIELD_NUM_NOTES, "NOTES"},
	{FIT_WORKOUT_STEP_FIELD_NUM_EQUIPMENT, "EQUIPMENT"},
	{FIT_WORKOUT_STEP_FIELD_NUM_SECONDARY_TARGET_TYPE, "SECONDARY_TARGET_TYPE"}
};

static _field_title exercise_title_mesg[FIT_EXERCISE_TITLE_MESG_FIELDS] = {
	{FIT_EXERCISE_TITLE_FIELD_NUM_WKT_STEP_NAME, "WKT_STEP_NAME"},
	{FIT_EXERCISE_TITLE_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_EXERCISE_TITLE_FIELD_NUM_EXERCISE_CATEGORY, "EXERCISE_CATEGORY"},
	{FIT_EXERCISE_TITLE_FIELD_NUM_EXERCISE_NAME, "EXERCISE_NAME"}
};

static _field_title schedule_mesg[FIT_SCHEDULE_MESG_FIELDS] = {
	{FIT_SCHEDULE_FIELD_NUM_SERIAL_NUMBER, "SERIAL_NUMBER"},
	{FIT_SCHEDULE_FIELD_NUM_TIME_CREATED, "TIME_CREATED"},
	{FIT_SCHEDULE_FIELD_NUM_SCHEDULED_TIME, "SCHEDULED_TIME"},
	{FIT_SCHEDULE_FIELD_NUM_MANUFACTURER, "MANUFACTURER"},
	{FIT_SCHEDULE_FIELD_NUM_PRODUCT, "PRODUCT"},
	{FIT_SCHEDULE_FIELD_NUM_COMPLETED, "COMPLETED"},
	{FIT_SCHEDULE_FIELD_NUM_TYPE, "TYPE"}
};

static _field_title totals_mesg[FIT_TOTALS_MESG_FIELDS] = {
	{FIT_TOTALS_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_TOTALS_FIELD_NUM_TIMER_TIME, "TIMER_TIME"},
	{FIT_TOTALS_FIELD_NUM_DISTANCE, "DISTANCE"},
	{FIT_TOTALS_FIELD_NUM_CALORIES, "CALORIES"},
	{FIT_TOTALS_FIELD_NUM_ELAPSED_TIME, "ELAPSED_TIME"},
	{FIT_TOTALS_FIELD_NUM_ACTIVE_TIME, "ACTIVE_TIME"},
	{FIT_TOTALS_FIELD_NUM_MESSAGE_INDEX, "MESSAGE_INDEX"},
	{FIT_TOTALS_FIELD_NUM_SESSIONS, "SESSIONS"},
	{FIT_TOTALS_FIELD_NUM_SPORT, "SPORT"}
};

static _field_title weight_scale_mesg[FIT_WEIGHT_SCALE_MESG_FIELDS] = {
	{FIT_WEIGHT_SCALE_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_WEIGHT, "WEIGHT"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_PERCENT_FAT, "PERCENT_FAT"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_PERCENT_HYDRATION, "PERCENT_HYDRATION"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_VISCERAL_FAT_MASS, "VISCERAL_FAT_MASS"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_BONE_MASS, "BONE_MASS"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_MUSCLE_MASS, "MUSCLE_MASS"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_BASAL_MET, "BASAL_MET"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_ACTIVE_MET, "ACTIVE_MET"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_USER_PROFILE_INDEX, "USER_PROFILE_INDEX"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_BMI, "BMI"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_PHYSIQUE_RATING, "PHYSIQUE_RATING"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_METABOLIC_AGE, "METABOLIC_AGE"},
	{FIT_WEIGHT_SCALE_FIELD_NUM_VISCERAL_FAT_RATING, "VISCERAL_FAT_RATING"}
};

static _field_title blood_pressure_mesg[FIT_BLOOD_PRESSURE_MESG_FIELDS] = {
	{FIT_BLOOD_PRESSURE_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_SYSTOLIC_PRESSURE, "SYSTOLIC_PRESSURE"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_DIASTOLIC_PRESSURE, "DIASTOLIC_PRESSURE"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_MEAN_ARTERIAL_PRESSURE, "MEAN_ARTERIAL_PRESSURE"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_MAP_3_SAMPLE_MEAN, "MAP_3_SAMPLE_MEAN"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_MAP_MORNING_VALUES, "MAP_MORNING_VALUES"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_MAP_EVENING_VALUES, "MAP_EVENING_VALUES"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_USER_PROFILE_INDEX, "USER_PROFILE_INDEX"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_HEART_RATE, "HEART_RATE"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_HEART_RATE_TYPE, "HEART_RATE_TYPE"},
	{FIT_BLOOD_PRESSURE_FIELD_NUM_STATUS, "STATUS"}
};

static _field_title monitoring_info_mesg[FIT_MONITORING_INFO_MESG_FIELDS] = {
	{FIT_MONITORING_INFO_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_MONITORING_INFO_FIELD_NUM_LOCAL_TIMESTAMP, "LOCAL_TIMESTAMP"}
};

static _field_title monitoring_mesg[FIT_MONITORING_MESG_FIELDS] = {
	{FIT_MONITORING_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_MONITORING_FIELD_NUM_DISTANCE, "DISTANCE"},
	{FIT_MONITORING_FIELD_NUM_CYCLES, "CYCLES"},
	{FIT_MONITORING_FIELD_NUM_ACTIVE_TIME, "ACTIVE_TIME"},
	{FIT_MONITORING_FIELD_NUM_LOCAL_TIMESTAMP, "LOCAL_TIMESTAMP"},
	{FIT_MONITORING_FIELD_NUM_CALORIES, "CALORIES"},
	{FIT_MONITORING_FIELD_NUM_DISTANCE_16, "DISTANCE_16"},
	{FIT_MONITORING_FIELD_NUM_CYCLES_16, "CYCLES_16"},
	{FIT_MONITORING_FIELD_NUM_ACTIVE_TIME_16, "ACTIVE_TIME_16"},
	{FIT_MONITORING_FIELD_NUM_DEVICE_INDEX, "DEVICE_INDEX"},
	{FIT_MONITORING_FIELD_NUM_ACTIVITY_TYPE, "ACTIVITY_TYPE"},
	{FIT_MONITORING_FIELD_NUM_ACTIVITY_SUBTYPE, "ACTIVITY_SUBTYPE"}
};

static _field_title monitoring_hr_data_mesg[FIT_MONITORING_HR_DATA_MESG_FIELDS] = {
	{FIT_MONITORING_HR_DATA_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_MONITORING_HR_DATA_FIELD_NUM_RESTING_HEART_RATE, "RESTING_HEART_RATE"},
	{FIT_MONITORING_HR_DATA_FIELD_NUM_CURRENT_DAY_RESTING_HEART_RATE, "CURRENT_DAY_RESTING_HEART_RATE"}
};

static _field_title hr_mesg[FIT_HR_MESG_FIELDS] = {
	{FIT_HR_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_HR_FIELD_NUM_EVENT_TIMESTAMP, "EVENT_TIMESTAMP"},
	{FIT_HR_FIELD_NUM_FRACTIONAL_TIMESTAMP, "FRACTIONAL_TIMESTAMP"},
	{FIT_HR_FIELD_NUM_TIME256, "TIME256"},
	{FIT_HR_FIELD_NUM_FILTERED_BPM, "FILTERED_BPM"},
	{FIT_HR_FIELD_NUM_EVENT_TIMESTAMP_12, "EVENT_TIMESTAMP_12"}
};

static _field_title ant_rx_mesg[FIT_ANT_RX_MESG_FIELDS] = {
	{FIT_ANT_RX_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_ANT_RX_FIELD_NUM_DATA, "DATA"},
	{FIT_ANT_RX_FIELD_NUM_FRACTIONAL_TIMESTAMP, "FRACTIONAL_TIMESTAMP"},
	{FIT_ANT_RX_FIELD_NUM_MESG_ID, "MESG_ID"},
	{FIT_ANT_RX_FIELD_NUM_MESG_DATA, "MESG_DATA"},
	{FIT_ANT_RX_FIELD_NUM_CHANNEL_NUMBER, "CHANNEL_NUMBER"}
};

static _field_title ant_tx_mesg[FIT_ANT_TX_MESG_FIELDS] = {
	{FIT_ANT_TX_FIELD_NUM_TIMESTAMP, "TIMESTAMP"},
	{FIT_ANT_TX_FIELD_NUM_DATA, "DATA"},
	{FIT_ANT_TX_FIELD_NUM_FRACTIONAL_TIMESTAMP, "FRACTIONAL_TIMESTAMP"},
	{FIT_ANT_TX_FIELD_NUM_MESG_ID, "MESG_ID"},
	{FIT_ANT_TX_FIELD_NUM_MESG_DATA, "MESG_DATA"},
	{FIT_ANT_TX_FIELD_NUM_CHANNEL_NUMBER, "CHANNEL_NUMBER"}
};

static _field_title exd_screen_configuration_mesg[FIT_EXD_SCREEN_CONFIGURATION_MESG_FIELDS] = {
	{FIT_EXD_SCREEN_CONFIGURATION_FIELD_NUM_SCREEN_INDEX, "SCREEN_INDEX"},
	{FIT_EXD_SCREEN_CONFIGURATION_FIELD_NUM_FIELD_COUNT, "FIELD_COUNT"},
	{FIT_EXD_SCREEN_CONFIGURATION_FIELD_NUM_LAYOUT, "LAYOUT"},
	{FIT_EXD_SCREEN_CONFIGURATION_FIELD_NUM_SCREEN_ENABLED, "SCREEN_ENABLED"}
};

static _field_title exd_data_field_configuration_mesg[FIT_EXD_DATA_FIELD_CONFIGURATION_MESG_FIELDS] = {
	{FIT_EXD_DATA_FIELD_CONFIGURATION_FIELD_NUM_SCREEN_INDEX, "SCREEN_INDEX"},
	{FIT_EXD_DATA_FIELD_CONFIGURATION_FIELD_NUM_CONCEPT_FIELD, "CONCEPT_FIELD"},
	{FIT_EXD_DATA_FIELD_CONFIGURATION_FIELD_NUM_FIELD_ID, "FIELD_ID"},
	{FIT_EXD_DATA_FIELD_CONFIGURATION_FIELD_NUM_CONCEPT_COUNT, "CONCEPT_COUNT"},
	{FIT_EXD_DATA_FIELD_CONFIGURATION_FIELD_NUM_DISPLAY_TYPE, "DISPLAY_TYPE"},
	{FIT_EXD_DATA_FIELD_CONFIGURATION_FIELD_NUM_TITLE, "TITLE"}
};

static _field_title exd_data_concept_configuration_mesg[FIT_EXD_DATA_CONCEPT_CONFIGURATION_MESG_FIELDS] = {
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_SCREEN_INDEX, "SCREEN_INDEX"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_CONCEPT_FIELD, "CONCEPT_FIELD"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_FIELD_ID, "FIELD_ID"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_CONCEPT_INDEX, "CONCEPT_INDEX"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_DATA_PAGE, "DATA_PAGE"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_CONCEPT_KEY, "CONCEPT_KEY"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_SCALING, "SCALING"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_DATA_UNITS, "DATA_UNITS"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_QUALIFIER, "QUALIFIER"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_DESCRIPTOR, "DESCRIPTOR"},
	{FIT_EXD_DATA_CONCEPT_CONFIGURATION_FIELD_NUM_IS_SIGNED, "IS_SIGNED"}
};

static _field_title hrv_mesg[FIT_HRV_MESG_FIELDS] = {
	{FIT_HRV_FIELD_NUM_TIME, "TIME"}
};

static _mesg_titles mesg_titles[MESG_TITLES] = {
	{FIT_MESG_NUM_FILE_ID, FIT_FILE_ID_MESG_FIELDS, file_id_mesg, "FILE_ID"},
	{FIT_MESG_NUM_FILE_CREATOR, FIT_FILE_CREATOR_MESG_FIELDS, file_creator_mesg, "FILE_CREATOR"},
	{FIT_MESG_NUM_SOFTWARE, FIT_SOFTWARE_MESG_FIELDS, software_mesg, "SOFTWARE"},
	{FIT_MESG_NUM_SLAVE_DEVICE, FIT_SLAVE_DEVICE_MESG_FIELDS, slave_device_mesg, "SLAVE_DEVICE"},
	{FIT_MESG_NUM_CAPABILITIES, FIT_CAPABILITIES_MESG_FIELDS, capabilities_mesg, "CAPABILITIES"},
	{FIT_MESG_NUM_FILE_CAPABILITIES, FIT_FILE_CAPABILITIES_MESG_FIELDS, file_capabilities_mesg, "FILE_CAPABILITIES"},
	{FIT_MESG_NUM_MESG_CAPABILITIES, FIT_MESG_CAPABILITIES_MESG_FIELDS, mesg_capabilities_mesg, "MESG_CAPABILITIES"},
	{FIT_MESG_NUM_FIELD_CAPABILITIES, FIT_FIELD_CAPABILITIES_MESG_FIELDS, field_capabilities_mesg, "FIELD_CAPABILITIES"},
	{FIT_MESG_NUM_DEVICE_SETTINGS, FIT_DEVICE_SETTINGS_MESG_FIELDS, device_settings_mesg, "DEVICE_SETTINGS"},
	{FIT_MESG_NUM_USER_PROFILE, FIT_USER_PROFILE_MESG_FIELDS, user_profile_mesg, "USER_PROFILE"},
	{FIT_MESG_NUM_HRM_PROFILE, FIT_HRM_PROFILE_MESG_FIELDS, hrm_profile_mesg, "HRM_PROFILE"},
	{FIT_MESG_NUM_SDM_PROFILE, FIT_SDM_PROFILE_MESG_FIELDS, sdm_profile_mesg, "SDM_PROFILE"},
	{FIT_MESG_NUM_BIKE_PROFILE, FIT_BIKE_PROFILE_MESG_FIELDS, bike_profile_mesg, "BIKE_PROFILE"},
	{FIT_MESG_NUM_CONNECTIVITY, FIT_CONNECTIVITY_MESG_FIELDS, connectivity_mesg, "CONNECTIVITY"},
	{FIT_MESG_NUM_ZONES_TARGET, FIT_ZONES_TARGET_MESG_FIELDS, zones_target_mesg, "ZONES_TARGET"},
	{FIT_MESG_NUM_SPORT, FIT_SPORT_MESG_FIELDS, sport_mesg, "SPORT"},
	{FIT_MESG_NUM_HR_ZONE, FIT_HR_ZONE_MESG_FIELDS, hr_zone_mesg, "HR_ZONE"},
	{FIT_MESG_NUM_SPEED_ZONE, FIT_SPEED_ZONE_MESG_FIELDS, speed_zone_mesg, "SPEED_ZONE"},
	{FIT_MESG_NUM_CADENCE_ZONE, FIT_CADENCE_ZONE_MESG_FIELDS, cadence_zone_mesg, "CADENCE_ZONE"},
	{FIT_MESG_NUM_POWER_ZONE, FIT_POWER_ZONE_MESG_FIELDS, power_zone_mesg, "POWER_ZONE"},
	{FIT_MESG_NUM_MET_ZONE, FIT_MET_ZONE_MESG_FIELDS, met_zone_mesg, "MET_ZONE"},
	{FIT_MESG_NUM_DIVE_SETTINGS, FIT_DIVE_SETTINGS_MESG_FIELDS, dive_settings_mesg, "DIVE_SETTINGS"},
	{FIT_MESG_NUM_GOAL, FIT_GOAL_MESG_FIELDS, goal_mesg, "GOAL"},
	{FIT_MESG_NUM_ACTIVITY, FIT_ACTIVITY_MESG_FIELDS, activity_mesg, "ACTIVITY"},
	{FIT_MESG_NUM_SESSION, FIT_SESSION_MESG_FIELDS, session_mesg, "SESSION"},
	{FIT_MESG_NUM_LAP, FIT_LAP_MESG_FIELDS, lap_mesg, "LAP"},
	{FIT_MESG_NUM_LENGTH, FIT_LENGTH_MESG_FIELDS, length_mesg, "LENGTH"},
	{FIT_MESG_NUM_RECORD, FIT_RECORD_MESG_FIELDS, record_mesg, "RECORD"},
	{FIT_MESG_NUM_EVENT, FIT_EVENT_MESG_FIELDS, event_mesg, "EVENT"},
	{FIT_MESG_NUM_DEVICE_INFO, FIT_DEVICE_INFO_MESG_FIELDS, device_info_mesg, "DEVICE_INFO"},
	{FIT_MESG_NUM_DEVICE_AUX_BATTERY_INFO, FIT_DEVICE_AUX_BATTERY_INFO_MESG_FIELDS, device_aux_battery_info_mesg, "DEVICE_AUX_BATTERY_INFO"},
	{FIT_MESG_NUM_TRAINING_FILE, FIT_TRAINING_FILE_MESG_FIELDS, training_file_mesg, "TRAINING_FILE"},
	{FIT_MESG_NUM_WEATHER_CONDITIONS, FIT_WEATHER_CONDITIONS_MESG_FIELDS, weather_conditions_mesg, "WEATHER_CONDITIONS"},
	{FIT_MESG_NUM_WEATHER_ALERT, FIT_WEATHER_ALERT_MESG_FIELDS, weather_alert_mesg, "WEATHER_ALERT"},
	{FIT_MESG_NUM_NMEA_SENTENCE, FIT_NMEA_SENTENCE_MESG_FIELDS, nmea_sentence_mesg, "NMEA_SENTENCE"},
	{FIT_MESG_NUM_AVIATION_ATTITUDE, FIT_AVIATION_ATTITUDE_MESG_FIELDS, aviation_attitude_mesg, "AVIATION_ATTITUDE"},
	{FIT_MESG_NUM_VIDEO_TITLE, FIT_VIDEO_TITLE_MESG_FIELDS, video_title_mesg, "VIDEO_TITLE"},
	{FIT_MESG_NUM_VIDEO_DESCRIPTION, FIT_VIDEO_DESCRIPTION_MESG_FIELDS, video_description_mesg, "VIDEO_DESCRIPTION"},
	{FIT_MESG_NUM_FIELD_DESCRIPTION, FIT_FIELD_DESCRIPTION_MESG_FIELDS, field_description_mesg, "FIELD_DESCRIPTION"},
	{FIT_MESG_NUM_DEVELOPER_DATA_ID, FIT_DEVELOPER_DATA_ID_MESG_FIELDS, developer_data_id_mesg, "DEVELOPER_DATA_ID"},
	{FIT_MESG_NUM_SET, FIT_SET_MESG_FIELDS, set_mesg, "SET"},
	{FIT_MESG_NUM_COURSE, FIT_COURSE_MESG_FIELDS, course_mesg, "COURSE"},
	{FIT_MESG_NUM_COURSE_POINT, FIT_COURSE_POINT_MESG_FIELDS, course_point_mesg, "COURSE_POINT"},
	{FIT_MESG_NUM_SEGMENT_ID, FIT_SEGMENT_ID_MESG_FIELDS, segment_id_mesg, "SEGMENT_ID"},
	{FIT_MESG_NUM_SEGMENT_LEADERBOARD_ENTRY, FIT_SEGMENT_LEADERBOARD_ENTRY_MESG_FIELDS, segment_leaderboard_entry_mesg, "SEGMENT_LEADERBOARD_ENTRY"},
	{FIT_MESG_NUM_SEGMENT_POINT, FIT_SEGMENT_POINT_MESG_FIELDS, segment_point_mesg, "SEGMENT_POINT"},
	{FIT_MESG_NUM_SEGMENT_LAP, FIT_SEGMENT_LAP_MESG_FIELDS, segment_lap_mesg, "SEGMENT_LAP"},
	{FIT_MESG_NUM_SEGMENT_FILE, FIT_SEGMENT_FILE_MESG_FIELDS, segment_file_mesg, "SEGMENT_FILE"},
	{FIT_MESG_NUM_WORKOUT, FIT_WORKOUT_MESG_FIELDS, workout_mesg, "WORKOUT"},
	{FIT_MESG_NUM_WORKOUT_SESSION, FIT_WORKOUT_SESSION_MESG_FIELDS, workout_session_mesg, "WORKOUT_SESSION"},
	{FIT_MESG_NUM_WORKOUT_STEP, FIT_WORKOUT_STEP_MESG_FIELDS, workout_step_mesg, "WORKOUT_STEP"},
	{FIT_MESG_NUM_EXERCISE_TITLE, FIT_EXERCISE_TITLE_MESG_FIELDS, exercise_title_mesg, "EXERCISE_TITLE"},
	{FIT_MESG_NUM_SCHEDULE, FIT_SCHEDULE_MESG_FIELDS, schedule_mesg, "SCHEDULE"},
	{FIT_MESG_NUM_TOTALS, FIT_TOTALS_MESG_FIELDS, totals_mesg, "TOTALS"},
	{FIT_MESG_NUM_WEIGHT_SCALE, FIT_WEIGHT_SCALE_MESG_FIELDS, weight_scale_mesg, "WEIGHT_SCALE"},
	{FIT_MESG_NUM_BLOOD_PRESSURE, FIT_BLOOD_PRESSURE_MESG_FIELDS, blood_pressure_mesg, "BLOOD_PRESSURE"},
	{FIT_MESG_NUM_MONITORING_INFO, FIT_MONITORING_INFO_MESG_FIELDS, monitoring_info_mesg, "MONITORING_INFO"},
	{FIT_MESG_NUM_MONITORING, FIT_MONITORING_MESG_FIELDS, monitoring_mesg, "MONITORING"},
	{FIT_MESG_NUM_MONITORING_HR_DATA, FIT_MONITORING_HR_DATA_MESG_FIELDS, monitoring_hr_data_mesg, "MONITORING_HR_DATA"},
	{FIT_MESG_NUM_HR, FIT_HR_MESG_FIELDS, hr_mesg, "HR"},
	{FIT_MESG_NUM_ANT_RX, FIT_ANT_RX_MESG_FIELDS, ant_rx_mesg, "ANT_RX"},
	{FIT_MESG_NUM_ANT_TX, FIT_ANT_TX_MESG_FIELDS, ant_tx_mesg, "ANT_TX"},
	{FIT_MESG_NUM_EXD_SCREEN_CONFIGURATION, FIT_EXD_SCREEN_CONFIGURATION_MESG_FIELDS, exd_screen_configuration_mesg, "EXD_SCREEN_CONFIGURATION"},
	{FIT_MESG_NUM_EXD_DATA_FIELD_CONFIGURATION, FIT_EXD_DATA_FIELD_CONFIGURATION_MESG_FIELDS, exd_data_field_configuration_mesg, "EXD_DATA_FIELD_CONFIGURATION"},
	{FIT_MESG_NUM_EXD_DATA_CONCEPT_CONFIGURATION, FIT_EXD_DATA_CONCEPT_CONFIGURATION_MESG_FIELDS, exd_data_concept_configuration_mesg, "EXD_DATA_CONCEPT_CONFIGURATION"},
	{FIT_MESG_NUM_HRV, FIT_HRV_MESG_FIELDS, hrv_mesg, "HRV"}
};

char *get_field_title (FIT_MESG_NUM mesg_num, FIT_UINT8 field_val) {
	int m, f;

	for (m = 0; m < MESG_TITLES; m++) {
		if (mesg_titles[m].g_mesg_num == mesg_num) {
			for (f = 0; f < mesg_titles[m].num_of_fields; f++) {
				if (mesg_titles[m].fields[f].f_val == field_val) {
					return mesg_titles[m].fields[f].f_title;
				}
			}
		}
	}

	return unknown;
}

char *get_mesg_title (FIT_MESG_NUM mesg_num) {
	int m;

	for (m = 0; m < MESG_TITLES; m++) {
		if (mesg_titles[m].g_mesg_num == mesg_num)
			return mesg_titles[m].mesg_title;
	}

	return unknown;
}
